
services:
  db:
    image: postgres:15-alpine
    container_name: apex_postgres_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: apexmotoparts_db
    ports:
      - "5437:5432"
    volumes:
      # Guarda los datos físicamente para no perderlos si se apaga el contenedor
      - apex_db_data:/var/lib/postgresql/data
      # Lee el archivo init.sql y crea las tablas automáticamente
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: apex_pgadmin
    restart: always
    environment:
      # Credenciales para entrar a tu panel visual de la base de datos
      PGADMIN_DEFAULT_EMAIL: admin@apexmotoparts.com
      PGADMIN_DEFAULT_PASSWORD: adminpassword123
    ports:
      # Entrarás a pgAdmin escribiendo localhost:5050 en tu navegador
      - "5050:80"
    depends_on:
      - db

volumes:
  apex_db_data: